apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: postgres-exporter
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: postgres-exporter
    app.kubernetes.io/part-of: kube-prometheus 
    app.kubernetes.io/version: 0.8.0
rules:
- apiGroups:      
  - authorization.k8s.io
  resources:      
  - podsecuritypolicies
  verbs:          
  - use
  resourceNames:  
  - prometheus-exporter