apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: postgres-exporter
    app.kubernetes.io/part-of: kube-prometheus 
    app.kubernetes.io/version: 0.8.0
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9187
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: postgres-exporter
    app.kubernetes.io/part-of: kube-prometheus 
